Repository Project-OpenBook/openbook-server, pull requests merged in 2024-07, with the labels that each got.

#61 Fix: 일반 유저가 승인되지 않은 행사를 조회할 수 있는 문제
  src/main/java/com/openbook/openbook/basicuser/service/UserEventService.java
Labels: fix

#63 Fix: 승인되지 않은 부스 조회시 에러 메세지 수정
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
Labels: fix

#67 Refactor: 도메인 서비스 분리
  src/main/java/com/openbook/openbook/administrator/AdminEventService.java
  src/main/java/com/openbook/openbook/basicuser/service/BasicUserService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutAreaService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventService.java
  src/main/java/com/openbook/openbook/booth/dto/BoothDTO.java
  src/main/java/com/openbook/openbook/booth/entity/Booth.java
  src/main/java/com/openbook/openbook/booth/entity/BoothLocation.java
  src/main/java/com/openbook/openbook/booth/repository/BoothLocationRepository.java
  src/main/java/com/openbook/openbook/booth/repository/BoothRepository.java
  src/main/java/com/openbook/openbook/booth/service/BoothService.java
  src/main/java/com/openbook/openbook/event/dto/EventDTO.java
  src/main/java/com/openbook/openbook/event/dto/EventLayoutDTO.java
  src/main/java/com/openbook/openbook/event/dto/LayoutAreaDTO.java
  src/main/java/com/openbook/openbook/event/entity/EventLayoutArea.java
  src/main/java/com/openbook/openbook/event/service/EventLayoutService.java
  src/main/java/com/openbook/openbook/event/service/EventService.java
  src/main/java/com/openbook/openbook/event/service/LayoutAreaService.java
  src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
  src/main/java/com/openbook/openbook/global/util/Formatter.java
  src/main/java/com/openbook/openbook/user/dto/UserDTO.java
  src/main/java/com/openbook/openbook/user/service/UserService.java
Labels: refactor

#70 Fix: 부스 태그 테이블 및 엔티티 수정
  src/main/java/com/openbook/openbook/booth/entity/Booth.java
  src/main/java/com/openbook/openbook/booth/entity/BoothTag.java
  src/main/java/com/openbook/openbook/booth/entity/BoothTagDetail.java
Labels: fix

#68 Refactor: ErrorCode 를 사용해 예외 처리
  src/main/java/com/openbook/openbook/administrator/AdminEventService.java
  src/main/java/com/openbook/openbook/basicuser/service/BasicUserService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventService.java
  src/main/java/com/openbook/openbook/booth/service/BoothService.java
  src/main/java/com/openbook/openbook/configuration/JwtAuthenticationFilter.java
  src/main/java/com/openbook/openbook/event/service/EventService.java
  src/main/java/com/openbook/openbook/event/service/LayoutAreaService.java
  src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/global/exception/OpenBookException.java
  src/main/java/com/openbook/openbook/global/util/S3Service.java
  src/main/java/com/openbook/openbook/user/service/UserService.java
Labels: refactor

#72 Fix: 알림 테이블 구성
  src/main/java/com/openbook/openbook/user/dto/AlarmType.java
  src/main/java/com/openbook/openbook/user/entity/Alarm.java
Labels: fix

#74 Feat: 부스 태그 등록
  src/main/java/com/openbook/openbook/basicuser/dto/request/BoothRegistrationRequest.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/booth/dto/BoothTagDTO.java
  src/main/java/com/openbook/openbook/booth/repository/BoothTagRepository.java
  src/main/java/com/openbook/openbook/booth/service/BoothTagService.java
Labels: feature

#76 Feat: 알림 생성 기능
  src/main/java/com/openbook/openbook/administrator/AdminEventService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventService.java
  src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
  src/main/java/com/openbook/openbook/user/dto/AlarmType.java
  src/main/java/com/openbook/openbook/user/entity/Alarm.java
  src/main/java/com/openbook/openbook/user/repository/AlarmRepository.java
  src/main/java/com/openbook/openbook/user/repository/UserRepository.java
  src/main/java/com/openbook/openbook/user/service/AlarmService.java
  src/main/java/com/openbook/openbook/user/service/UserService.java
Labels: feature

#80 Feat: 알림 조회 API
  src/main/java/com/openbook/openbook/basicuser/controller/BasicUserController.java
  src/main/java/com/openbook/openbook/basicuser/dto/response/AlarmData.java
  src/main/java/com/openbook/openbook/basicuser/service/BasicUserService.java
  src/main/java/com/openbook/openbook/user/dto/UserPublicData.java
  src/main/java/com/openbook/openbook/user/repository/AlarmRepository.java
  src/main/java/com/openbook/openbook/user/service/AlarmService.java
Labels: feature

#85 Feat: 알림 단건 삭제 API
  src/main/java/com/openbook/openbook/basicuser/controller/BasicUserController.java
  src/main/java/com/openbook/openbook/basicuser/service/BasicUserService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/user/repository/AlarmRepository.java
  src/main/java/com/openbook/openbook/user/service/AlarmService.java
Labels: feature

#82 Fix: 부스 상세에 행사 이름 추가
  src/main/java/com/openbook/openbook/basicuser/dto/response/BoothBasicData.java
  src/main/java/com/openbook/openbook/basicuser/dto/response/BoothDetail.java
Labels: fix

#81 Fix: 405 예외 상황 처리
  src/main/java/com/openbook/openbook/global/exception/GlobalControllerAdvice.java
Labels: fix

#87 Fix: 부스 태그 데이터 리스트 형식으로 수정
  src/main/java/com/openbook/openbook/basicuser/dto/request/BoothRegistrationRequest.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
Labels: fix

#89 Feat: 행사 태그 등록 기능
  src/main/java/com/openbook/openbook/basicuser/dto/request/EventRegistrationRequest.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventService.java
  src/main/java/com/openbook/openbook/event/entity/Event.java
  src/main/java/com/openbook/openbook/event/entity/EventTag.java
  src/main/java/com/openbook/openbook/event/entity/EventTagDetail.java
  src/main/java/com/openbook/openbook/event/repository/EventTagRepository.java
  src/main/java/com/openbook/openbook/event/service/EventService.java
  src/main/java/com/openbook/openbook/event/service/EventTagService.java
Labels: feature

#91 Feat: 부스 태그 검색 결과 조회 API
  src/main/java/com/openbook/openbook/basicuser/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/booth/repository/BoothTagRepository.java
  src/main/java/com/openbook/openbook/booth/service/BoothTagService.java
Labels: feature

#95 Fix: 부스와 행사 태그 필드명 수정
  src/main/java/com/openbook/openbook/booth/entity/BoothTag.java
  src/main/java/com/openbook/openbook/booth/repository/BoothTagRepository.java
  src/main/java/com/openbook/openbook/booth/service/BoothTagService.java
  src/main/java/com/openbook/openbook/event/entity/EventTag.java
  src/main/java/com/openbook/openbook/event/service/EventTagService.java
Labels: fix

#100 Fix: 행사와 부스 조회 결과에 태그 정보 추가
  src/main/java/com/openbook/openbook/administrator/AdminEventService.java
  src/main/java/com/openbook/openbook/administrator/dto/AdminEventData.java
  src/main/java/com/openbook/openbook/basicuser/dto/response/BoothBasicData.java
  src/main/java/com/openbook/openbook/basicuser/dto/response/BoothDetail.java
  src/main/java/com/openbook/openbook/basicuser/dto/response/EventBasicData.java
  src/main/java/com/openbook/openbook/basicuser/dto/response/EventDetail.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventService.java
  src/main/java/com/openbook/openbook/booth/entity/Booth.java
  src/main/java/com/openbook/openbook/booth/entity/BoothTag.java
  src/main/java/com/openbook/openbook/booth/repository/BoothTagRepository.java
  src/main/java/com/openbook/openbook/booth/service/BoothTagService.java
  src/main/java/com/openbook/openbook/event/repository/EventTagRepository.java
  src/main/java/com/openbook/openbook/event/service/EventTagService.java
  src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
  src/main/java/com/openbook/openbook/eventmanager/dto/BoothManageData.java
Labels: fix, refactor

#103 Fix: 부스 조회에 관리자인지 판별하는 값 추가
  src/main/java/com/openbook/openbook/basicuser/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/basicuser/dto/response/BoothDetail.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
Labels: fix

#99 Feat: 받은 알림 전체 삭제 API
  src/main/java/com/openbook/openbook/basicuser/controller/BasicUserController.java
  src/main/java/com/openbook/openbook/basicuser/service/BasicUserService.java
  src/main/java/com/openbook/openbook/user/repository/AlarmRepository.java
  src/main/java/com/openbook/openbook/user/service/AlarmService.java
Labels: feature

#106 Docs: refactor issue templates 추가
  .github/ISSUE_TEMPLATE/refactor-idea.md
Labels: documentation

#109 Feat: 관리하는 행사 목록 조회 API
  src/main/java/com/openbook/openbook/event/controller/AdminEventController.java
  src/main/java/com/openbook/openbook/event/controller/ManagerEventController.java
  src/main/java/com/openbook/openbook/event/controller/UserEventController.java
  src/main/java/com/openbook/openbook/event/controller/response/AdminEventData.java
  src/main/java/com/openbook/openbook/event/controller/response/ManagerEventData.java
  src/main/java/com/openbook/openbook/event/controller/response/UserEventData.java
  src/main/java/com/openbook/openbook/event/repository/EventRepository.java
  src/main/java/com/openbook/openbook/event/service/AdminEventService.java
  src/main/java/com/openbook/openbook/event/service/ManagerEventService.java
  src/main/java/com/openbook/openbook/event/service/UserEventService.java
  src/main/java/com/openbook/openbook/event/service/core/EventService.java
  src/main/java/com/openbook/openbook/event/service/core/EventTagService.java
Labels: feature

#110 Feat: 부스 이름으로 부스 검색
  src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/booth/repository/BoothRepository.java
  src/main/java/com/openbook/openbook/booth/repository/BoothTagRepository.java
  src/main/java/com/openbook/openbook/booth/service/UserBoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothTagService.java
Labels: feature

#111 Fix: 태그 정보를 입력하지 않는 경우 발생하는 오류
  src/main/java/com/openbook/openbook/booth/controller/request/BoothRegistrationRequest.java
  src/main/java/com/openbook/openbook/booth/service/UserBoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothTagService.java
  src/main/java/com/openbook/openbook/event/service/UserEventService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/global/util/TagUtil.java
Labels: fix

#112 Feat: 토큰 정보 확인 API
  src/main/java/com/openbook/openbook/configuration/JwtAuthenticationFilter.java
  src/main/java/com/openbook/openbook/global/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/openbook/openbook/global/util/JwtUtils.java
  src/main/java/com/openbook/openbook/global/util/TokenProvider.java
  src/main/java/com/openbook/openbook/user/controller/UserController.java
  src/main/java/com/openbook/openbook/user/controller/response/TokenInfo.java
  src/main/java/com/openbook/openbook/user/dto/UserPublicData.java
  src/main/java/com/openbook/openbook/user/service/UserCommonService.java
Labels: feature
