Repository Project-OpenBook/openbook-server, pull requests merged in 2024-05, with the labels that each got.

#1 Docs: PR template 생성
  docs/pull_request_template.md
Labels: documentation

#2 Docs: issue templates 생성
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/suggest.md
Labels: documentation

#4 Feat: 도메인 엔티티 구현
  build.gradle
  src/main/java/com/openbook/openbook/OpenbookApplication.java
  src/main/java/com/openbook/openbook/booth/dto/BoothStatus.java
  src/main/java/com/openbook/openbook/booth/entity/Booth.java
  src/main/java/com/openbook/openbook/booth/entity/BoothLocation.java
  src/main/java/com/openbook/openbook/booth/entity/BoothTag.java
  src/main/java/com/openbook/openbook/booth/entity/BoothTagDetail.java
  src/main/java/com/openbook/openbook/event/dto/EventLayoutAreaStatus.java
  src/main/java/com/openbook/openbook/event/dto/EventLayoutType.java
  src/main/java/com/openbook/openbook/event/dto/EventStatus.java
  src/main/java/com/openbook/openbook/event/entity/Event.java
  src/main/java/com/openbook/openbook/event/entity/EventLayout.java
  src/main/java/com/openbook/openbook/event/entity/EventLayoutArea.java
  src/main/java/com/openbook/openbook/event/entity/EventTag.java
  src/main/java/com/openbook/openbook/event/entity/EventTagDetail.java
  src/main/java/com/openbook/openbook/global/EntityBasicTime.java
  src/main/java/com/openbook/openbook/user/dto/AlarmType.java
  src/main/java/com/openbook/openbook/user/dto/UserRole.java
  src/main/java/com/openbook/openbook/user/entity/Alarm.java
  src/main/java/com/openbook/openbook/user/entity/User.java
Labels: feature

#7 Feat: 회원가입 API
  build.gradle
  src/main/java/com/openbook/openbook/config/BCryptPasswordConfig.java
  src/main/java/com/openbook/openbook/config/SecurityConfig.java
  src/main/java/com/openbook/openbook/global/ResponseMessage.java
  src/main/java/com/openbook/openbook/user/UserController.java
  src/main/java/com/openbook/openbook/user/UserRepository.java
  src/main/java/com/openbook/openbook/user/UserService.java
  src/main/java/com/openbook/openbook/user/dto/SignUpRequest.java
  src/main/java/com/openbook/openbook/user/entity/User.java
Labels: feature

#10 Fix: 부스 테이블 필드 추가
  src/main/java/com/openbook/openbook/booth/entity/Booth.java
Labels: fix

#13 Feat: 예외 전역 처리
  src/main/java/com/openbook/openbook/config/SecurityConfig.java
  src/main/java/com/openbook/openbook/global/ResponseMessage.java
  src/main/java/com/openbook/openbook/global/exception/CustomAccessDeniedHandler.java
  src/main/java/com/openbook/openbook/global/exception/GlobalControllerAdvice.java
  src/main/java/com/openbook/openbook/global/exception/OpenBookException.java
  src/main/java/com/openbook/openbook/user/UserService.java
Labels: feature, fix

#14 Feat: 아마존 S3에 파일 등록 및 삭제 기능
  build.gradle
  src/main/java/com/openbook/openbook/config/S3Config.java
  src/main/java/com/openbook/openbook/global/S3Service.java
  src/main/java/com/openbook/openbook/global/exception/GlobalControllerAdvice.java
Labels: feature

#16 Feat: 로그인 기능
  build.gradle
  src/main/java/com/openbook/openbook/config/JwtAuthenticationFilter.java
  src/main/java/com/openbook/openbook/config/SecurityConfig.java
  src/main/java/com/openbook/openbook/global/JwtUtils.java
  src/main/java/com/openbook/openbook/global/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/openbook/openbook/user/UserController.java
  src/main/java/com/openbook/openbook/user/UserService.java
  src/main/java/com/openbook/openbook/user/dto/request/LoginRequest.java
  src/main/java/com/openbook/openbook/user/dto/request/SignUpRequest.java
Labels: feature

#19 Feat: 행사 등록 요청 API
  build.gradle
  src/main/java/com/openbook/openbook/event/controller/UserEventController.java
  src/main/java/com/openbook/openbook/event/controller/request/EventRegistrationRequest.java
  src/main/java/com/openbook/openbook/event/dto/EventLayoutData.java
  src/main/java/com/openbook/openbook/event/dto/LayoutAreaData.java
  src/main/java/com/openbook/openbook/event/entity/Event.java
  src/main/java/com/openbook/openbook/event/entity/EventLayout.java
  src/main/java/com/openbook/openbook/event/entity/EventLayoutArea.java
  src/main/java/com/openbook/openbook/event/entity/dto/EventLayoutAreaStatus.java
  src/main/java/com/openbook/openbook/event/entity/dto/EventLayoutType.java
  src/main/java/com/openbook/openbook/event/entity/dto/EventStatus.java
  src/main/java/com/openbook/openbook/event/repository/EventLayoutAreaRepository.java
  src/main/java/com/openbook/openbook/event/repository/EventLayoutRepository.java
  src/main/java/com/openbook/openbook/event/repository/EventRepository.java
  src/main/java/com/openbook/openbook/event/service/EventLayoutAreaService.java
  src/main/java/com/openbook/openbook/event/service/EventLayoutService.java
  src/main/java/com/openbook/openbook/event/service/EventService.java
  src/main/java/com/openbook/openbook/global/S3Service.java
  src/main/java/com/openbook/openbook/global/exception/GlobalControllerAdvice.java
  src/main/java/com/openbook/openbook/user/UserRepository.java
Labels: feature

#25 Feat: 승인 요청된 행사 목록 확인
  src/main/java/com/openbook/openbook/config/SecurityConfig.java
  src/main/java/com/openbook/openbook/event/controller/AdminEventController.java
  src/main/java/com/openbook/openbook/event/controller/response/PageResponse.java
  src/main/java/com/openbook/openbook/event/dto/AdminEventData.java
  src/main/java/com/openbook/openbook/event/repository/EventRepository.java
  src/main/java/com/openbook/openbook/event/service/AdminEventService.java
  src/main/java/com/openbook/openbook/global/Formatter.java
Labels: feature

#23 Feat: 부스 등록 기능 API
  settings.gradle
  src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/booth/dto/request/BoothRegistrationRequest.java
  src/main/java/com/openbook/openbook/booth/entity/BoothProduct.java
  src/main/java/com/openbook/openbook/booth/entity/BoothReservation.java
  src/main/java/com/openbook/openbook/booth/entity/BoothReservationDetail.java
  src/main/java/com/openbook/openbook/booth/repository/BoothLocationRepository.java
  src/main/java/com/openbook/openbook/booth/repository/BoothRepository.java
  src/main/java/com/openbook/openbook/booth/service/BoothLocationService.java
  src/main/java/com/openbook/openbook/booth/service/BoothService.java
  src/main/java/com/openbook/openbook/event/entity/EventLayoutArea.java
  src/main/java/com/openbook/openbook/event/repository/EventLayoutAreaRepository.java
  src/main/java/com/openbook/openbook/event/repository/EventRepository.java
  src/main/java/com/openbook/openbook/user/UserService.java
Labels: feature

#27 Refactor: 행사 API 관련
  src/main/java/com/openbook/openbook/event/controller/UserEventController.java
Labels: refactor

#30 Feat: 행사 배치도 상태 조회
  src/main/java/com/openbook/openbook/basicuser/controller/UserEventController.java
  src/main/java/com/openbook/openbook/basicuser/dto/EventLayoutCreateData.java
  src/main/java/com/openbook/openbook/basicuser/dto/LayoutAreaCreateData.java
  src/main/java/com/openbook/openbook/basicuser/dto/LayoutAreaStatusData.java
  src/main/java/com/openbook/openbook/basicuser/dto/response/EventLayoutStatus.java
  src/main/java/com/openbook/openbook/basicuser/service/EventLayoutAreaService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutAreaService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventService.java
  src/main/java/com/openbook/openbook/event/repository/EventLayoutAreaRepository.java
  src/main/java/com/openbook/openbook/event/repository/EventLayoutRepository.java
Labels: feature

#33 Feat: 행사 상태 변경 API
  src/main/java/com/openbook/openbook/administrator/AdminEventController.java
  src/main/java/com/openbook/openbook/administrator/AdminEventService.java
  src/main/java/com/openbook/openbook/administrator/dto/request/EventStatusUpdateRequest.java
  src/main/java/com/openbook/openbook/event/entity/Event.java
Labels: feature

#36 Fix: 부스 신청시 구역 정보가 저장되지 않는 문제
  src/main/java/com/openbook/openbook/basicuser/dto/request/BoothRegistrationRequest.java
  src/main/java/com/openbook/openbook/basicuser/service/BoothLocationService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutAreaService.java
  src/main/java/com/openbook/openbook/event/entity/EventLayoutArea.java
  src/main/java/com/openbook/openbook/event/repository/EventLayoutAreaRepository.java
Labels: fix

#32 Feat: 해당 행사에 대한 부스 등록 신청 목록 조회
  src/main/java/com/openbook/openbook/booth/repository/BoothRepository.java
  src/main/java/com/openbook/openbook/event/repository/EventLayoutAreaRepository.java
  src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
  src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
  src/main/java/com/openbook/openbook/eventmanager/dto/BoothAreaData.java
  src/main/java/com/openbook/openbook/eventmanager/dto/BoothManageData.java
Labels: feature

#43 Feat: 부스 등록 신청 상태 변경 API
  src/main/java/com/openbook/openbook/booth/entity/Booth.java
  src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
  src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
  src/main/java/com/openbook/openbook/eventmanager/dto/BoothStatusUpdateRequest.java
Labels: feature
