Repository Project-OpenBook/openbook-server, pull requests merged in 2024-09, with the labels that each got.

#185 Feat: 행사 리뷰 등록 API
  src/main/java/com/openbook/openbook/event/controller/UserEventController.java
  src/main/java/com/openbook/openbook/event/controller/request/EventReviewRegisterRequest.java
  src/main/java/com/openbook/openbook/event/dto/EventReviewDto.java
  src/main/java/com/openbook/openbook/event/entity/EventReviewImage.java
  src/main/java/com/openbook/openbook/event/repository/EventReviewImageRepository.java
  src/main/java/com/openbook/openbook/event/repository/EventReviewRepository.java
  src/main/java/com/openbook/openbook/event/service/common/CommonEventReviewService.java
  src/main/java/com/openbook/openbook/event/service/core/EventReviewService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
Labels: feature

#188 Feat: 행사 리뷰 목록 조회 API
  src/main/java/com/openbook/openbook/configuration/JwtAuthenticationFilter.java
  src/main/java/com/openbook/openbook/event/controller/UserEventController.java
  src/main/java/com/openbook/openbook/event/controller/response/EventReviewImageData.java
  src/main/java/com/openbook/openbook/event/controller/response/EventReviewResponse.java
  src/main/java/com/openbook/openbook/event/repository/EventReviewImageRepository.java
  src/main/java/com/openbook/openbook/event/repository/EventReviewRepository.java
  src/main/java/com/openbook/openbook/event/service/common/CommonEventReviewService.java
  src/main/java/com/openbook/openbook/event/service/core/EventReviewService.java
  src/main/java/com/openbook/openbook/global/util/TokenProvider.java
  src/main/java/com/openbook/openbook/user/dto/UserDetail.java
  src/main/java/com/openbook/openbook/user/dto/UserPublicData.java
Labels: feature

#187 Feat: 부스별 저장된 예약 정보 목록 조회
  src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/booth/controller/response/BoothReservationDetailResponse.java
  src/main/java/com/openbook/openbook/booth/controller/response/BoothReservationsResponse.java
  src/main/java/com/openbook/openbook/booth/repository/BoothReservationDetailRepository.java
  src/main/java/com/openbook/openbook/booth/repository/BoothReservationRepository.java
  src/main/java/com/openbook/openbook/booth/service/common/CommonReservationService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothReservationDetailService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothReservationService.java
Labels: feature

#191 Feat: 행사 리뷰 단 건 조회 API
  src/main/java/com/openbook/openbook/event/controller/UserEventController.java
  src/main/java/com/openbook/openbook/event/service/common/CommonEventReviewService.java
  src/main/java/com/openbook/openbook/event/service/core/EventReviewService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
Labels: feature

#192 Fix: 일반 조회 api는 토큰 없이 호출할 수 있도록 설정
  src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/booth/controller/response/BoothDetail.java
  src/main/java/com/openbook/openbook/booth/service/BoothCommonService.java
  src/main/java/com/openbook/openbook/configuration/SecurityConfig.java
  src/main/java/com/openbook/openbook/event/controller/UserEventController.java
  src/main/java/com/openbook/openbook/event/controller/response/EventDetail.java
  src/main/java/com/openbook/openbook/event/service/EventCommonService.java
Labels: feature

#193 Feat: 부스 관리자 시점 예약 정보 목록 조회
  src/main/java/com/openbook/openbook/booth/controller/ManagerBoothController.java
  src/main/java/com/openbook/openbook/booth/controller/response/BoothReserveDetailManageResponse.java
  src/main/java/com/openbook/openbook/booth/controller/response/BoothReserveManageResponse.java
  src/main/java/com/openbook/openbook/booth/entity/BoothReservationDetail.java
  src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
Labels: feature

#196 Feat: 행사 리뷰 삭제 API
  src/main/java/com/openbook/openbook/event/controller/UserEventController.java
  src/main/java/com/openbook/openbook/event/service/common/CommonEventReviewService.java
  src/main/java/com/openbook/openbook/event/service/core/EventReviewService.java
Labels: feature

#202 Feat: 북마크 도메인 생성
  src/main/java/com/openbook/openbook/user/entity/Bookmark.java
  src/main/java/com/openbook/openbook/user/entity/dto/BookmarkType.java
Labels: feature

#209 Feat: 부스 리뷰 작성 API
  src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/booth/controller/request/BoothReviewRegisterRequest.java
  src/main/java/com/openbook/openbook/booth/dto/BoothReviewDto.java
  src/main/java/com/openbook/openbook/booth/repository/BoothReviewRepository.java
  src/main/java/com/openbook/openbook/booth/service/common/CommonBoothReviewService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothReviewService.java
Labels: feature

#219 Fix: 부스 도메인의 조회 api 오류
  src/main/java/com/openbook/openbook/api/booth/BoothController.java
  src/main/java/com/openbook/openbook/api/booth/BoothNoticeController.java
  src/main/java/com/openbook/openbook/api/booth/BoothProductController.java
  src/main/java/com/openbook/openbook/api/booth/BoothReservationController.java
  src/main/java/com/openbook/openbook/api/booth/BoothReviewController.java
  src/main/java/com/openbook/openbook/service/booth/BoothNoticeService.java
  src/main/java/com/openbook/openbook/service/booth/dto/BoothReservationDetailDto.java
Labels: fix

#218 Feat: 북마크 생성 API
  src/main/java/com/openbook/openbook/api/user/BookmarkController.java
  src/main/java/com/openbook/openbook/api/user/request/BookmarkRequest.java
  src/main/java/com/openbook/openbook/domain/user/dto/BookmarkType.java
  src/main/java/com/openbook/openbook/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/repository/user/BookmarkRepository.java
  src/main/java/com/openbook/openbook/service/user/BookmarkService.java
Labels: feature

#222 Feat: 북마크한 행사와 부스 목록을 조회하는 API
  build.gradle
  src/main/java/com/openbook/openbook/api/user/BookmarkController.java
  src/main/java/com/openbook/openbook/api/user/response/BookmarkResponse.java
  src/main/java/com/openbook/openbook/repository/user/BookmarkRepository.java
  src/main/java/com/openbook/openbook/service/user/BookmarkService.java
  src/main/java/com/openbook/openbook/service/user/dto/BookmarkDto.java
Labels: feature

#224 Fix: 부스 운영 시간이 아닌 다른 날짜의 예약을 추가할 경우 에러처리
  src/main/java/com/openbook/openbook/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/service/booth/BoothReservationService.java
Labels: fix

#225 Feat: 북마크를 취소하는 API
  src/main/java/com/openbook/openbook/api/user/BookmarkController.java
  src/main/java/com/openbook/openbook/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/repository/user/BookmarkRepository.java
  src/main/java/com/openbook/openbook/service/user/BookmarkService.java
Labels: feature

#229 Feat: 부스 리뷰 목록 조회 API
  src/main/java/com/openbook/openbook/api/booth/BoothReviewController.java
  src/main/java/com/openbook/openbook/api/booth/response/BoothReviewResponse.java
  src/main/java/com/openbook/openbook/configuration/SecurityConfig.java
  src/main/java/com/openbook/openbook/repository/booth/BoothReviewRepository.java
  src/main/java/com/openbook/openbook/service/booth/BoothReviewService.java
  src/main/java/com/openbook/openbook/service/booth/dto/BoothReviewDto.java
Labels: feature

#231 Feat: 부스 리뷰 단 건 조회
  src/main/java/com/openbook/openbook/api/booth/BoothReviewController.java
  src/main/java/com/openbook/openbook/service/booth/BoothReviewService.java
Labels: feature

#227 Fix: 이미 존재하는 예약의 동일 날짜를 가진 새 예약을 등록할 경우
  src/main/java/com/openbook/openbook/repository/booth/BoothReservationDetailRepository.java
  src/main/java/com/openbook/openbook/repository/booth/BoothReservationRepository.java
  src/main/java/com/openbook/openbook/service/booth/BoothReservationDetailService.java
  src/main/java/com/openbook/openbook/service/booth/BoothReservationService.java
Labels: fix

#234 Feat: 행사 리뷰를 수정하는 기능
  src/main/java/com/openbook/openbook/api/event/EventReviewController.java
  src/main/java/com/openbook/openbook/api/event/request/EventReviewModifyRequest.java
  src/main/java/com/openbook/openbook/domain/event/EventReview.java
  src/main/java/com/openbook/openbook/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/service/event/EventReviewService.java
Labels: feature

#237 Feat: 부스 리뷰 삭제하는 API
  src/main/java/com/openbook/openbook/api/booth/BoothReviewController.java
  src/main/java/com/openbook/openbook/service/booth/BoothReviewService.java
Labels: feature

#239 Feat: 부스 상품 삭제 API
  src/main/java/com/openbook/openbook/api/booth/BoothProductController.java
  src/main/java/com/openbook/openbook/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/service/booth/BoothProductService.java
Labels: feature

#241 Refactor: 행사 리뷰 이미지 서비스 분리
  src/main/java/com/openbook/openbook/service/event/EventReviewImageService.java
  src/main/java/com/openbook/openbook/service/event/EventReviewService.java
Labels: refactor

#244 Fix: 부스 리뷰 등록시 이미지 등록 문제 수정
  src/main/java/com/openbook/openbook/api/booth/request/BoothReviewRegisterRequest.java
  src/main/java/com/openbook/openbook/service/booth/BoothReviewService.java
Labels: fix

#247 Feat: 행사 공지사항 수정 API
  src/main/java/com/openbook/openbook/api/event/EventNoticeController.java
  src/main/java/com/openbook/openbook/api/event/request/EventNoticeModifyRequest.java
  src/main/java/com/openbook/openbook/domain/event/EventNotice.java
  src/main/java/com/openbook/openbook/service/event/EventNoticeService.java
  src/main/java/com/openbook/openbook/service/event/dto/EventNoticeUpdateData.java
Labels: feature
