Repository Project-OpenBook/openbook-server, pull requests merged in 2024-10, with the labels that each got.

#245 Fix: 이미 작성한 리뷰가 있는 경우 작성하지 못하도록 수정
  src/main/java/com/openbook/openbook/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/repository/booth/BoothReviewRepository.java
  src/main/java/com/openbook/openbook/repository/event/EventReviewRepository.java
  src/main/java/com/openbook/openbook/service/booth/BoothReviewService.java
  src/main/java/com/openbook/openbook/service/event/EventReviewService.java
Labels: fix

#251 Chore: gradle.yml파일 추가
  .github/workflows/gradle.yml
  build.gradle
Labels: feature

#248 Feat: 부스 수정 API
  src/main/java/com/openbook/openbook/api/booth/BoothController.java
  src/main/java/com/openbook/openbook/api/booth/request/BoothModifyRequest.java
  src/main/java/com/openbook/openbook/domain/booth/Booth.java
  src/main/java/com/openbook/openbook/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/repository/booth/BoothTagRepository.java
  src/main/java/com/openbook/openbook/service/booth/BoothService.java
  src/main/java/com/openbook/openbook/service/booth/BoothTagService.java
  src/main/java/com/openbook/openbook/service/booth/dto/BoothUpdateData.java
Labels: feature

#252 Feat: 부스 리뷰 수정 API
  src/main/java/com/openbook/openbook/api/booth/BoothReviewController.java
  src/main/java/com/openbook/openbook/api/booth/request/BoothReviewModifyRequest.java
  src/main/java/com/openbook/openbook/domain/booth/BoothReview.java
  src/main/java/com/openbook/openbook/service/booth/BoothReviewService.java
  src/main/java/com/openbook/openbook/service/booth/dto/BoothReviewUpdateData.java
Labels: feature

#256 Feat: 부스 상품 카테고리 삭제 API
  src/main/java/com/openbook/openbook/api/booth/BoothProductController.java
  src/main/java/com/openbook/openbook/domain/booth/BoothProduct.java
  src/main/java/com/openbook/openbook/domain/booth/BoothProductCategory.java
  src/main/java/com/openbook/openbook/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/repository/booth/BoothProductCategoryRepository.java
  src/main/java/com/openbook/openbook/repository/booth/BoothProductRepository.java
  src/main/java/com/openbook/openbook/service/booth/BoothProductCategoryService.java
  src/main/java/com/openbook/openbook/service/booth/BoothProductService.java
Labels: feature

#259 Chore: CD 작업 추가
  .github/workflows/gradle.yml
  Dockerfile
Labels: feature

#258 Fix: 본인 부스 조회시 데이터 추가
  src/main/java/com/openbook/openbook/api/booth/response/BoothManageData.java
Labels: refactor

#262 Fix: reservation 객체 생성시 price 추가
  .github/workflows/gradle.yml
  src/main/java/com/openbook/openbook/service/booth/BoothReservationService.java
Labels: fix

#263 Feat: 부스 공지 수정 API
  .github/workflows/gradle.yml
  src/main/java/com/openbook/openbook/api/booth/BoothNoticeController.java
  src/main/java/com/openbook/openbook/api/booth/request/BoothNoticeModifyRequest.java
  src/main/java/com/openbook/openbook/domain/booth/BoothNotice.java
  src/main/java/com/openbook/openbook/service/booth/BoothNoticeService.java
  src/main/java/com/openbook/openbook/service/booth/dto/BoothNoticeUpdateData.java
Labels: feature

#266 Refactor: @ResponseStatus 를 사용하도록 변경
  src/main/java/com/openbook/openbook/api/booth/BoothController.java
  src/main/java/com/openbook/openbook/api/booth/BoothNoticeController.java
  src/main/java/com/openbook/openbook/api/booth/BoothProductController.java
  src/main/java/com/openbook/openbook/api/booth/BoothReservationController.java
  src/main/java/com/openbook/openbook/api/booth/BoothReviewController.java
  src/main/java/com/openbook/openbook/api/event/EventController.java
  src/main/java/com/openbook/openbook/api/event/EventNoticeController.java
  src/main/java/com/openbook/openbook/api/event/EventReviewController.java
  src/main/java/com/openbook/openbook/api/user/AlarmController.java
  src/main/java/com/openbook/openbook/api/user/BookmarkController.java
  src/main/java/com/openbook/openbook/api/user/UserController.java
Labels: refactor

#268 Feat: 부스 공지 삭제 API
  .github/workflows/gradle.yml
  src/main/java/com/openbook/openbook/api/booth/BoothNoticeController.java
  src/main/java/com/openbook/openbook/service/booth/BoothNoticeService.java
Labels: feature

#270 Fix: 공지 등록시 이미지 null 일 때 처리
  src/main/java/com/openbook/openbook/service/booth/BoothNoticeService.java
  src/main/java/com/openbook/openbook/service/booth/BoothReviewService.java
  src/main/java/com/openbook/openbook/service/event/EventNoticeService.java
Labels: fix

#272 Chore: CICD 파일 주석 해제 및 배포 스크립트 수정
  .github/workflows/gradle.yml
Labels: refactor

#265 Feat: 부스 상품 수정 API
  src/main/java/com/openbook/openbook/api/booth/BoothProductController.java
  src/main/java/com/openbook/openbook/api/booth/request/ProductModifyRequest.java
  src/main/java/com/openbook/openbook/domain/booth/BoothProduct.java
  src/main/java/com/openbook/openbook/exception/ErrorCode.java
  src/main/java/com/openbook/openbook/repository/booth/BoothProductImageRepository.java
  src/main/java/com/openbook/openbook/service/booth/BoothProductCategoryService.java
  src/main/java/com/openbook/openbook/service/booth/BoothProductImageService.java
  src/main/java/com/openbook/openbook/service/booth/BoothProductService.java
  src/main/java/com/openbook/openbook/service/booth/dto/BoothProductUpdateData.java
Labels: feature

#274 Refactor: 예약 등록시 여러 날짜와 시간 등록 관련 개선
  src/main/java/com/openbook/openbook/api/booth/request/ReserveRegistrationRequest.java
  src/main/java/com/openbook/openbook/service/booth/BoothReservationService.java
Labels: refactor

#277 Feat: 부스 목록 조회에서의 행사 필터링 기능 추가
  src/main/java/com/openbook/openbook/api/booth/BoothController.java
  src/main/java/com/openbook/openbook/repository/booth/BoothRepository.java
  src/main/java/com/openbook/openbook/service/booth/BoothService.java
Labels: feature

#276 Refactor: 은행명, 계좌 번호 응답 추가
  .github/workflows/gradle.yml
  src/main/java/com/openbook/openbook/api/booth/response/BoothDetail.java
Labels: refactor

#281 Feat: 유저 프로필 정보 조회 API
  src/main/java/com/openbook/openbook/api/user/UserController.java
  src/main/java/com/openbook/openbook/api/user/response/UserProfileResponse.java
  src/main/java/com/openbook/openbook/service/user/UserService.java
  src/main/java/com/openbook/openbook/service/user/dto/UserProfileDto.java
Labels: feature

#282 Chore: 배포 설정 수정
  .github/workflows/gradle.yml
  Dockerfile
Labels: refactor

#284 Refactor: 부스 단일 정보 조회시 태그 id 추가
  src/main/java/com/openbook/openbook/api/booth/response/BoothDetail.java
Labels: refactor

#286 Feat: 북마크 여부 확인 API
  src/main/java/com/openbook/openbook/api/user/BookmarkController.java
  src/main/java/com/openbook/openbook/service/user/BookmarkService.java
Labels: feature

#289 Feat: 프로필 수정 API
  src/main/java/com/openbook/openbook/api/user/UserController.java
  src/main/java/com/openbook/openbook/api/user/request/UserModifyRequest.java
  src/main/java/com/openbook/openbook/domain/user/User.java
  src/main/java/com/openbook/openbook/service/user/UserService.java
  src/main/java/com/openbook/openbook/service/user/dto/UserUpdateDto.java
Labels: feature
