Repository Project-OpenBook/openbook-server, pull requests merged in 2024-08, with the labels that each got.

#116 Feat: 행사 검색 API
  src/main/java/com/openbook/openbook/event/controller/UserEventController.java
  src/main/java/com/openbook/openbook/event/repository/EventRepository.java
  src/main/java/com/openbook/openbook/event/repository/EventTagRepository.java
  src/main/java/com/openbook/openbook/event/service/UserEventService.java
  src/main/java/com/openbook/openbook/event/service/core/EventService.java
  src/main/java/com/openbook/openbook/event/service/core/EventTagService.java
Labels: feature

#117 Feat: 자신의 부스 목록 조회 API
  src/main/java/com/openbook/openbook/booth/controller/ManagerBoothController.java
  src/main/java/com/openbook/openbook/booth/controller/response/BoothManageData.java
  src/main/java/com/openbook/openbook/booth/repository/BoothRepository.java
  src/main/java/com/openbook/openbook/booth/repository/BoothTagRepository.java
  src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothService.java
Labels: feature

#120 Refactor: 부스 검색시 파라미터 값 통합 요청
  src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/booth/service/UserBoothService.java
Labels: refactor

#121 Refactor: 중복되는 기능 쿼리 통합
  src/main/java/com/openbook/openbook/event/repository/EventRepository.java
  src/main/java/com/openbook/openbook/event/service/core/EventService.java
Labels: refactor

#122 Feat: 부스 단건 삭제 API
  src/main/java/com/openbook/openbook/booth/controller/ManagerBoothController.java
  src/main/java/com/openbook/openbook/booth/entity/BoothArea.java
  src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothAreaService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
Labels: feature

#126 Add: 행사 게시판 기능을 위한 엔티티
  src/main/java/com/openbook/openbook/event/entity/Event.java
  src/main/java/com/openbook/openbook/event/entity/EventBoard.java
  src/main/java/com/openbook/openbook/event/entity/dto/EventBoardType.java
Labels: feature

#132 Add: 부스 상품 기능 개발을 위한 엔티티
  src/main/java/com/openbook/openbook/booth/entity/Booth.java
  src/main/java/com/openbook/openbook/booth/entity/BoothProduct.java
  src/main/java/com/openbook/openbook/booth/entity/BoothProductImage.java
Labels: feature

#131 Add: 부스 서비스 예약 기능을 위한 엔티티 추가
  src/main/java/com/openbook/openbook/booth/entity/Booth.java
  src/main/java/com/openbook/openbook/booth/entity/BoothReservation.java
  src/main/java/com/openbook/openbook/booth/entity/BoothReservationDetail.java
  src/main/java/com/openbook/openbook/booth/entity/dto/BoothReservationStatus.java
Labels: feature

#136 Feat: 부스 상품 등록 API
  src/main/java/com/openbook/openbook/booth/controller/ManagerBoothController.java
  src/main/java/com/openbook/openbook/booth/controller/request/ProductRegistrationRequest.java
  src/main/java/com/openbook/openbook/booth/dto/BoothProductDto.java
  src/main/java/com/openbook/openbook/booth/repository/BoothProductImageRepository.java
  src/main/java/com/openbook/openbook/booth/repository/BoothProductRepository.java
  src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothProductService.java
  src/main/java/com/openbook/openbook/event/controller/ManagerEventController.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
Labels: feature

#138 Feat: 행사 공지사항 등록 API
  src/main/java/com/openbook/openbook/event/controller/ManagerEventController.java
  src/main/java/com/openbook/openbook/event/controller/request/NoticeRegisterRequest.java
  src/main/java/com/openbook/openbook/event/dto/EventNoticeDto.java
  src/main/java/com/openbook/openbook/event/entity/Event.java
  src/main/java/com/openbook/openbook/event/entity/EventNotice.java
  src/main/java/com/openbook/openbook/event/entity/dto/EventNoticeType.java
  src/main/java/com/openbook/openbook/event/repository/EventNoticeRepository.java
  src/main/java/com/openbook/openbook/event/service/ManagerEventService.java
  src/main/java/com/openbook/openbook/event/service/core/EventNoticeService.java
Labels: feature

#139 Feat: 부스 예약 서비스 등록
  src/main/java/com/openbook/openbook/booth/controller/ManagerBoothController.java
  src/main/java/com/openbook/openbook/booth/controller/request/ReserveRegistrationRequest.java
  src/main/java/com/openbook/openbook/booth/dto/BoothReservationDTO.java
  src/main/java/com/openbook/openbook/booth/repository/BoothReservationDetailRepository.java
  src/main/java/com/openbook/openbook/booth/repository/BoothReservationRepository.java
  src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothReservationDetailService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothReservationService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
Labels: feature

#141 Add: 부스 공지사항 기능을 위한 엔티티 추가
  src/main/java/com/openbook/openbook/booth/entity/Booth.java
  src/main/java/com/openbook/openbook/booth/entity/BoothNotice.java
  src/main/java/com/openbook/openbook/booth/entity/dto/BoothNoticeType.java
Labels: feature

#143 Feat: 행사 공지사항 목록 조회
  src/main/java/com/openbook/openbook/event/controller/ManagerEventController.java
  src/main/java/com/openbook/openbook/event/controller/UserEventController.java
  src/main/java/com/openbook/openbook/event/controller/request/EventNoticeRegisterRequest.java
  src/main/java/com/openbook/openbook/event/controller/response/EventNoticeData.java
  src/main/java/com/openbook/openbook/event/repository/EventNoticeRepository.java
  src/main/java/com/openbook/openbook/event/service/EventCommonService.java
  src/main/java/com/openbook/openbook/event/service/EventLayoutCommonService.java
  src/main/java/com/openbook/openbook/event/service/ManagerEventService.java
  src/main/java/com/openbook/openbook/event/service/core/EventNoticeService.java
Labels: feature

#150 Feat: 행사 공지 단 건 조회 API
  src/main/java/com/openbook/openbook/event/controller/UserEventController.java
  src/main/java/com/openbook/openbook/event/controller/response/EventNoticeData.java
  src/main/java/com/openbook/openbook/event/service/EventCommonService.java
  src/main/java/com/openbook/openbook/event/service/core/EventNoticeService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
Labels: feature

#153 Feat: 부스 상품 카테고리 기능
  src/main/java/com/openbook/openbook/booth/controller/request/ProductRegistrationRequest.java
  src/main/java/com/openbook/openbook/booth/dto/BoothProductDto.java
  src/main/java/com/openbook/openbook/booth/entity/Booth.java
  src/main/java/com/openbook/openbook/booth/entity/BoothProduct.java
  src/main/java/com/openbook/openbook/booth/entity/BoothProductCategory.java
  src/main/java/com/openbook/openbook/booth/repository/BoothProductCategoryRepository.java
  src/main/java/com/openbook/openbook/booth/service/EventManagerBoothService.java
  src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothProductService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
Labels: feature, refactor

#155 Feat: 부스 공지사항 등록
  src/main/java/com/openbook/openbook/booth/controller/ManagerBoothController.java
  src/main/java/com/openbook/openbook/booth/controller/request/BoothNoticeRegisterRequest.java
  src/main/java/com/openbook/openbook/booth/dto/BoothNoticeDto.java
  src/main/java/com/openbook/openbook/booth/repository/BoothNoticeRepository.java
  src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothNoticeService.java
Labels: feature

#158 Feat: 부스 공지 목록 조회 API
  src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/booth/controller/response/BoothNoticeResponse.java
  src/main/java/com/openbook/openbook/booth/repository/BoothNoticeRepository.java
  src/main/java/com/openbook/openbook/booth/service/UserBoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothNoticeService.java
Labels: feature

#162 Feat: 부스 상품 카테고리 추가 API
  src/main/java/com/openbook/openbook/booth/controller/ManagerBoothController.java
  src/main/java/com/openbook/openbook/booth/controller/request/ProductCategoryRegister.java
  src/main/java/com/openbook/openbook/booth/repository/BoothProductCategoryRepository.java
  src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothProductService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
Labels: feature

#166 Feat: 행사 공지사항 삭제 API
  src/main/java/com/openbook/openbook/event/controller/ManagerEventController.java
  src/main/java/com/openbook/openbook/event/dto/EventNoticeDto.java
  src/main/java/com/openbook/openbook/event/service/ManagerEventService.java
  src/main/java/com/openbook/openbook/event/service/core/EventNoticeService.java
  src/main/java/com/openbook/openbook/global/util/S3Service.java
Labels: feature, refactor

#168 Feat: 부스 공지 단 건 조회
  src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/booth/service/BoothCommonService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothNoticeService.java
  src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
Labels: feature, refactor

#174 Fix: 부스 검색 중복 값 제거
  src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/booth/repository/BoothTagRepository.java
Labels: fix

#175 Feat: 부스의 상품을 카테고리 별로 조회하는 API
  src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/booth/controller/response/BoothProductResponse.java
  src/main/java/com/openbook/openbook/booth/controller/response/CategoryProductsResponse.java
  src/main/java/com/openbook/openbook/booth/dto/ProductImageDto.java
  src/main/java/com/openbook/openbook/booth/repository/BoothProductImageRepository.java
  src/main/java/com/openbook/openbook/booth/repository/BoothProductRepository.java
  src/main/java/com/openbook/openbook/booth/service/common/CommonProductService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothProductService.java
Labels: feature

#178 Refactor: 부스 공지 사진 업로드 수정
  src/main/java/com/openbook/openbook/booth/dto/BoothNoticeDto.java
  src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
  src/main/java/com/openbook/openbook/booth/service/core/BoothNoticeService.java
Labels: refactor

#182 Feat: 행사 리뷰 기능 개발에 필요한 엔티티
  src/main/java/com/openbook/openbook/event/entity/Event.java
  src/main/java/com/openbook/openbook/event/entity/EventReview.java
  src/main/java/com/openbook/openbook/event/entity/EventReviewImage.java
Labels: feature

#183 Feat: 카테고리의 상품을 조회하는 API
  src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/booth/service/common/CommonProductService.java
Labels: feature
