Repository Project-OpenBook/openbook-server, pull requests merged in 2024-06, with the labels that each got.

#45 Feat: 진행중인 모든 부스 목록 조회 API
  src/main/java/com/openbook/openbook/basicuser/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/basicuser/dto/response/BoothBasicData.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/booth/repository/BoothRepository.java
Labels: feature

#47 Feat: 행사 상세 정보 조회
  src/main/java/com/openbook/openbook/basicuser/controller/UserEventController.java
  src/main/java/com/openbook/openbook/basicuser/dto/response/EventDetail.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventService.java
  src/main/java/com/openbook/openbook/booth/repository/BoothRepository.java
  src/main/java/com/openbook/openbook/global/util/JsonService.java
Labels: feature

#50 Feat: 부스 상세 정보 조회 API
  src/main/java/com/openbook/openbook/basicuser/controller/UserBoothController.java
  src/main/java/com/openbook/openbook/basicuser/dto/response/BoothDetail.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/booth/repository/BoothRepository.java
Labels: feature

#53 Fix: 부스 상세 정보 추가 및 시간 포멧팅
  src/main/java/com/openbook/openbook/basicuser/dto/response/BoothDetail.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/global/util/Formatter.java
Labels: fix

#55 Add: 부스 계좌 은행 추가
  .DS_Store
  src/main/java/com/openbook/openbook/basicuser/dto/request/BoothRegistrationRequest.java
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/booth/entity/Booth.java
Labels: fix

#57 Refactor: s3 파일 업로드 코드
  src/main/java/com/openbook/openbook/basicuser/service/UserBoothService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutService.java
  src/main/java/com/openbook/openbook/basicuser/service/UserEventService.java
  src/main/java/com/openbook/openbook/global/util/S3Service.java
Labels: refactor

#59 Fix: 종료된 행사의 필터링 조건
  src/main/java/com/openbook/openbook/event/repository/EventRepository.java
Labels: fix
